### ISSUE TITLE
[Insight] First level service should not be present in global configuration files

### ISSUE THREAD

**Issue by garak** [PUGX/badge-poser#93]
**[in app/config/config_dev.yml, line 5](https://github.com/PUGX/badge-poser/blob/master/app/config/config_dev.yml#L5)**

> A global service has been detected in your configuration file (service `stats_persister`). You should consider storing it in a bundle configuration.

```
imports:
    - { resource: config.yml }

services:
    stats_persister:
        class: PUGX\StatsBundle\Service\NullPersister
    stats_reader:
        class: PUGX\StatsBundle\Service\NullReader

framework:
```

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/e576013d-97f5-4292-8d37-7655a09138ea/analyses/2)_
